### ISSUE TITLE
Unable to see name of container when using dark mode in Unraid

### ISSUE THREAD

**Issue by mmartial** [phyzical/docker.labelInjector#3]
**Is your feature request related to a problem? Please describe.**
Adding a picture to show what I see when trying to use the tool from the UI

**Describe the solution you'd like**
Dark-mode awareness

<img width="487" alt="Screenshot 2024-10-01 at 13 29 02" src="https://github.com/user-attachments/assets/4c243e38-3a25-4123-9b6d-7a9c23d87387">

**Comment by phyzical** [comment]
Ah its the dropdown itself, on it.

**Comment by phyzical** [comment]
ive hard coded the text to black in the latest version, ill take a stab at proper dark mode at some point.

**Comment by mmartial** [comment]
tested and looks great, thank you

**Comment by mmartial** [comment]
Reporting that the issue is also present in the "Summary of updates" page

**Comment by mmartial** [comment]
I am unclear if the plugin is causing this side effect, but if I manually add a label from the Docker Edit page, the label does not get applied to the container

**Comment by phyzical** [comment]
Just pushed a fix for the summary page

hmm i dont think this plugin should have any effect on the edit page tbh.

I also added a page to show that nothing actually occured, and some other stuff.

The other thing to note is that if you dont actually press ok on the summary window itll save the template but will not actually take effect until you manually edit the container again (if thats what you mean by the "side effect")

If not lm repro wise is there any pattern of events? and ill try to see if i can replicate a issue

**Comment by mmartial** [comment]
I am unsure if this is a side effect or a glitch on my end, so I did not open a new bug; I mostly noted it.
Thanks for fixing the summary window
