### ISSUE TITLE
file ownership issue

### ISSUE THREAD

**Issue by mmartial** [phyzical/docker.labelInjector#4]
**Describe the bug**
Unraid's plugin installation extracts the plugin as root (at least for 6.12.13)
The files are created with the same permissions as the owner of the files.
This propagates into all the directory tree including /

```bash
tar tvfz docker.labelInjector-2024.10.02.txz
drwxr-xr-x  0 phyzical staff       0 Jul 24 09:38 ./
```
which appears to be `501` user.

This cause an issue for example when trying to `ssh` into the system
```
Authentication refused: bad ownership or modes for directory /
```

**To Reproduce**
Install the plugin, the ownership of / and sub directories up to `/usr/local/emhttp/plugins` is also modified

```bash
cd /
ls -al
total 20
drwxr-xr-x   21  501 games   460 Jul 24 09:38 ./
drwxr-xr-x   21  501 games   460 Jul 24 09:38 ../
[...]
drwxr-xr-x    1  501 games   240 Jul 24 09:38 usr/
```

**Expected behavior**
Plugin files are owned by `root:root` or this is a problem with Unraid as well
Note this is also true of the other docker plugin.

**Unraid version**
6.12.13

**Comment by mmartial** [comment]
Mentioning this post as a potential workaround for generating the archive
https://unix.stackexchange.com/questions/285237/tar-without-preserving-user

**Comment by phyzical** [comment]
@mmartial thanks i got to be honest this entire flow was based of how https://github.com/scolcipitato/folder.view/
did it

so im a total noob with it all 😆.

Maybe im better off looking at how dynamix does it, as i think they use workflows to automate it a bit better.

ill look at it later today 👍

**Comment by phyzical** [comment]
Should be resolved by #5

**Comment by phyzical** [comment]
ive republished all the versions so you may need to reinstall to verify LMK if you notice its still acting up permission wise

**Comment by mmartial** [comment]
Downloaded the latest `.txz` and confirmed `0:0` as expected from the changes.
I will report if I see a new issue, but thanks for updating this.

**Comment by mmartial** [comment]
FYSA, this post was recommended on the Unraid Discord
https://forums.unraid.net/topic/103886-permissions-on-files-installed-by-plugins/

**Comment by phyzical** [comment]
@mmartial thanks ill chuck that script into the workflow to avoid regressing on this again
