### ISSUE TITLE
plugin: bad file MD5

### ISSUE THREAD

**Issue by ssersh** [phyzical/docker.labelInjector#6]
Install Plugin

plugin: installing: docker.labelInjector.plg
Executing hook script: pre_plugin_checks
plugin: downloading: docker.labelInjector.plg ... done

plugin: downloading: docker.labelInjector-2024.10.02.txz ... done

plugin: bad file MD5: /boot/config/plugins/docker.labelInjector/docker.labelInjector-2024.10.02.txz
Executing hook script: gui_search_post_hook.sh
Executing hook script: post_plugin_checks

**Comment by phyzical** [comment]
@ssersh should also be resolved in this plugin LMK if you notice otherwise
