### ISSUE TITLE
Add ability to escape backticks

### ISSUE THREAD

**Issue by andrebrait** [phyzical/docker.labelInjector#9]
**Is your feature request related to a problem? Please describe.**
Not a problem itself, but basically there are times where we need to use backticks on Docker labels (e.g. adding a Host rule for Traefik, such as the one below, but the plugin always replaced backticks with quotation marks.

```
Host(`subdomain.domain.com`)
```

**Describe the solution you'd like**
A way to escape the backtick so it really becomes a backtick.

**Describe alternatives you've considered**
None?

**Additional context**
Most software uses a backslash to escape character sequences. Perhaps this could be one? e.g.

```
Host(\`subdomain.domain.com\`)
```

**Comment by phyzical** [comment]
ill consider that as a workaround, but tbh that logic replacing ` with " was a hack in of itself. 

ill have another stab at doing it properly, if not ill try escaping 👍

**Comment by phyzical** [comment]
@andrebrait sadly i couldnt avoid the hack, but what ive done instead is \\` will be the way to have quotes going forward, so in the next version just use ` as you want and it should work as expected.

LMK if you notice otherwise

**Comment by andrebrait** [comment]
> @andrebrait sadly i couldnt avoid the hack, but what ive done instead is \\\` will be the way to have quotes going forward, so in the next version just use ` as you want and it should work as expected.
> 
> LMK if you notice otherwise

Any reason why that would be better than escaping actual quotation marks (e.g. `\"`)?

**Comment by phyzical** [comment]
its something weird specific to choices.js lib, basically no matter how i try to "add" a new choice option it gets converting to a label of "[object Object]" on submit, 

even if i try being checky with the url  encoded version of a quote.

<img width="830" alt="image" src="https://github.com/user-attachments/assets/80a8bc52-57f5-46af-8dda-0a0a7bfb4fb5">

Im sure there is a way but every time ive tried i hit my 1 hour limit of eh this works 😆

**Comment by andrebrait** [comment]
Ah, yes. The wonders of JavaScript.

Most likely it's evaluating that somewhere and somehow it ends up concatenating the object with something and the coercion rule probably falls onto `a.toString() + b` or something.
